### ISSUE TITLE
File.exists? is deprecated in Ruby 3.1.0

### ISSUE THREAD

**Issue by cpence** [yohasebe/engtagger#17]
Quick fix: change all `File.exists?` to `File.exist?`.

**Comment by yohasebe** [comment]
Oh, I didn't know that. Thank you for the heads up. I'll make a change sometime soon.

**Comment by cpence** [comment]
Excellent, thanks (and thanks for the great gem!).

**Comment by yohasebe** [comment]
Fixed. Thanks again!
