### ISSUE TITLE
Postpositive adjectives aren't handled correctly

### ISSUE THREAD

**Issue by grv87** [yohasebe/engtagger#5]
[Postpositive adjectives](https://en.wikipedia.org/wiki/Postpositive_adjective) aren't handled correctly:

```ruby
puts tgr.add_tags("She stands with her arms akimbo.")
```
```
   <prp>She</prp> <vbz>stands</vbz> <in>with</in> <prps>her</prps> <nns>arms</nns> <nn>akimbo</nn> <pp>.</pp>
```

`akimbo` should be tagged as adjective (maybe with some special tag for postpositive), but it is tagged as noun.

**Comment by yohasebe** [comment]
Thanks for the report.  As engtagger is statistically based, it often gives wrong tags to words that are not frequent and it would be difficult to deal with individual cases.  Sorry about that...
