### ISSUE TITLE
verb detected as noun

### ISSUE THREAD

**Issue by lindt** [yohasebe/engtagger#8]
engtagger is nice, because binding is so easy and no java 150 MB package is needed for usage.
would like to stick to it, but need a proper way to find if a sentence contains verbs.
currently I got some false positives from engtagger. One is the example below. Hope there is a way to fix it.
Thanks.

```
> tagger.add_tags('the system detects the car')
=> "<det>the</det> <nn>system</nn> <nns>detects</nns> <det>the</det> <nn>car</nn>"
```

`detects` should be detected as `vbz`.

Is there a way of updating the pos_words.hash to be more precise?
Or is there a way that too low probabilities are ignored?
Or that the probability together with the list of possible pos_tags is returned?

**Comment by dpoetzsch** [comment]
Another problematic sentence is

`I share a meal with you`

**Comment by yohasebe** [comment]
Sorry for the belated response.  EngTagger is based on a Perl module called Lingua::EN::Tagger, and any problems that could occur with that module should occur with EngTagger too.

I would like to see if there's a way to fix, but unfortunately I cannot say it will be very soon.
